site_name: synbconvert
nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: api.md
  - CLI Reference: cli.md
theme:
  name: material
  favicon: img/favicon.png
repo_name: alpine-data/synbconvert
repo_url: https://github.com/alpine-data/synbconvert
edit_uri: edit/feature/documentation/docs
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - mkdocs-click
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css