[tool.poetry]
name = "synapse-nbconvert"
version = "0.1.0"
description = "A simple command line tool to convert Python files to Synapse Notebooks and vice versa."
authors = ["Michael Wellner <michaelwellner@kpmg.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
behave = "^1.2.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
